/* empty css                      */import{S as l,N as d}from"./assets/vendor-Sm41FR0M.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&s(r)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",function(){new l(".core-swiper",{modules:[d],breakpoints:{374:{slidesPerView:1.1,spaceBetween:20,centeredSlides:!1},1439:{slidesPerView:4,spaceBetween:20,centeredSlides:!1}},loop:!0,slideClass:"core-swiper-slide",wrapperClass:"core-swiper-wrapper",direction:"horizontal",navigation:{nextEl:".custom-next-first",prevEl:".custom-prev-first"},on:{reachBeginning:function(){document.querySelector(".custom-prev").classList.add("swiper-button-disabled")},reachEnd:function(){document.querySelector(".custom-next").classList.add("swiper-button-disabled")}}}),new l(".gallery-swiper",{modules:[d],breakpoints:{374:{slidesPerView:1.1,spaceBetween:20,centeredSlides:!1},1439:{slidesPerView:4,spaceBetween:20,centeredSlides:!1}},loop:!0,slideClass:"gallery-swiper-slide",wrapperClass:"gallery-swiper-wrapper",direction:"horizontal",navigation:{nextEl:".custom-next-gallery",prevEl:".custom-prev-gallery"},on:{reachBeginning:function(){document.querySelector(".custom-prev").classList.add("swiper-button-disabled")},reachEnd:function(){document.querySelector(".custom-next").classList.add("swiper-button-disabled")}}})});document.querySelectorAll(".faq-acc-el-trigger").forEach(i=>{i.addEventListener("click",()=>{const n=i.closest(".faq-acc-el"),o=n.querySelector(".faq-acc-el-descr-frame");n.classList.contains("open")?(n.classList.remove("open"),o.style.maxHeight="0"):(n.classList.add("open"),o.style.maxHeight=o.scrollHeight+"px")})});document.addEventListener("DOMContentLoaded",()=>{const i=document.querySelector(".menu-button"),n=i.querySelector(".icon"),o=document.querySelector(".modal"),s=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const r=`
<svg width="36" height="24" viewBox="0 0 36 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M0 24V21H36V24H0ZM0 13.5V10.5H36V13.5H0ZM0 3V0H36V3H0Z" fill="#1D1D1F" />
</svg>
    `,a=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12.8 38L10 35.2L21.2 24L10 12.8L12.8 10L24 21.2L35.2 10L38 12.8L26.8 24L38 35.2L35.2 38L24 26.8L12.8 38Z" fill="#1D1D1F" />
</svg>
    `;i.addEventListener("click",()=>{t=!t,n.innerHTML=t?a:r,t?u():c()}),s.forEach(p=>p.addEventListener("click",()=>{c(),n.innerHTML=r,t=!1})),window.addEventListener("scroll",f);function u(){o.style.display="block"}function c(){o.style.display="none"}function f(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function i(){const s=document.getElementById("site-header");return s?s.offsetHeight:0}function n(s){const e=document.getElementById(s);if(!e)return;const t=i(),r=e.getBoundingClientRect().top+window.pageYOffset-t;window.scrollTo({top:r,behavior:"smooth"})}document.querySelectorAll('a[href^="#"]').forEach(s=>{s.addEventListener("click",function(e){const t=this.getAttribute("href");if(t.startsWith("index.html#")||t.startsWith("http"))return;e.preventDefault();const r=t.substring(1);n(r)})});const o=window.location.hash;if(o){const s=o.substring(1);setTimeout(()=>{n(s)},1e3)}});
//# sourceMappingURL=index.js.map
