import{S as l,N as d}from"./assets/vendor-Sm41FR0M.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",function(){new l(".core-swiper",{modules:[d],breakpoints:{374:{slidesPerView:1.1,spaceBetween:20,centeredSlides:!1},1439:{slidesPerView:4,spaceBetween:20,centeredSlides:!1}},loop:!0,slideClass:"core-swiper-slide",wrapperClass:"core-swiper-wrapper",direction:"horizontal",navigation:{nextEl:".custom-next-first",prevEl:".custom-prev-first"},on:{reachBeginning:function(){document.querySelector(".custom-prev").classList.add("swiper-button-disabled")},reachEnd:function(){document.querySelector(".custom-next").classList.add("swiper-button-disabled")}}}),new l(".gallery-swiper",{modules:[d],breakpoints:{374:{slidesPerView:1.1,spaceBetween:20,centeredSlides:!1},1439:{slidesPerView:4,spaceBetween:20,centeredSlides:!1}},loop:!0,slideClass:"gallery-swiper-slide",wrapperClass:"gallery-swiper-wrapper",direction:"horizontal",navigation:{nextEl:".custom-next-gallery",prevEl:".custom-prev-gallery"},on:{reachBeginning:function(){document.querySelector(".custom-prev").classList.add("swiper-button-disabled")},reachEnd:function(){document.querySelector(".custom-next").classList.add("swiper-button-disabled")}}})});document.querySelectorAll(".faq-acc-el-trigger").forEach(r=>{r.addEventListener("click",()=>{const n=r.closest(".faq-acc-el"),s=n.querySelector(".faq-acc-el-descr-frame");n.classList.contains("open")?(n.classList.remove("open"),s.style.maxHeight="0"):(n.classList.add("open"),s.style.maxHeight=s.scrollHeight+"px")})});document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector(".menu-button"),n=r.querySelector(".icon"),s=document.querySelector(".modal"),o=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const c=`
<svg width="36" height="24" viewBox="0 0 36 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M0 24V21H36V24H0ZM0 13.5V10.5H36V13.5H0ZM0 3V0H36V3H0Z" fill="#1D1D1F" />
</svg>
    `,a=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12.8 38L10 35.2L21.2 24L10 12.8L12.8 10L24 21.2L35.2 10L38 12.8L26.8 24L38 35.2L35.2 38L24 26.8L12.8 38Z" fill="#1D1D1F" />
</svg>
    `;r.addEventListener("click",()=>{t=!t,n.innerHTML=t?a:c,t?u():i()}),o.forEach(f=>f.addEventListener("click",()=>{i(),n.innerHTML=c,t=!1})),window.addEventListener("scroll",p);function u(){s.style.display="block"}function i(){s.style.display="none"}function p(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function r(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function n(o){const e=document.getElementById(o);if(!e)return;const t=r(),c=e.getBoundingClientRect().top+window.pageYOffset-t;window.scrollTo({top:c,behavior:"smooth"})}document.querySelectorAll('a[href^="#"]').forEach(o=>{o.addEventListener("click",function(e){const t=this.getAttribute("href");if(t.startsWith("index.html#")||t.startsWith("http"))return;e.preventDefault();const c=t.substring(1);n(c)})});const s=window.location.hash;if(s){const o=s.substring(1);setTimeout(()=>{n(o)},1e3)}});document.addEventListener("DOMContentLoaded",function(){const r=document.getElementById("cookie-popup"),n=document.getElementById("accept-cookies"),s=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(r.style.display="block"),n.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),r.style.display="none"}),s.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),r.style.display="none"})});
//# sourceMappingURL=index.js.map
